RejestOsob/Controllers/LostPersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RejestOsob.Models;

namespace RejestOsob.Controllers
{
    public class LostPersonsController : Controller
    {
        private PersonEntities db = new PersonEntities();

        // GET: LostPersons









        public ActionResult Index(int GenderSelected=0)
        {
            
            
                var items = db.Gender.ToList();
               
                    ViewBag.data = items;
                var lostPerson = db.LostPerson.ToList();


                if (GenderSelected == 0)
                {
                    lostPerson = db.LostPerson.ToList();
                }
                else
                 lostPerson = db.LostPerson.Where(a => a.Gender1.Id == GenderSelected).ToList();

                return View(lostPerson.ToList());
            
        }



       




        // GET: LostPersons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LostPerson lostPerson = db.LostPerson.Find(id);
            if (lostPerson == null)
            {
                return HttpNotFound();
            }
            return View(lostPerson);
        }
        [Authorize]
        // GET: LostPersons/Create
        public ActionResult Create()
        {
            ViewBag.Gender = new SelectList(db.Gender, "Id", "Name");
            return View();
        }

        // POST: LostPersons/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdPerson,name,lastname,BDate,Photo,Describe,Gender,LostDate,LostPlace")] LostPerson lostPerson)
        {
            if (ModelState.IsValid)
            {
                db.LostPerson.Add(lostPerson);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Gender = new SelectList(db.Gender, "Id", "Name", lostPerson.Gender);
            return View(lostPerson);
        }
        [Authorize(Roles = "Administrator")]
        // GET: LostPersons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LostPerson lostPerson = db.LostPerson.Find(id);
            if (lostPerson == null)
            {
                return HttpNotFound();
            }
            ViewBag.Gender = new SelectList(db.Gender, "Id", "Name", lostPerson.Gender);
            return View(lostPerson);
        }

        // POST: LostPersons/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdPerson,name,lastname,BDate,Photo,Describe,Gender,LostDate,LostPlace")] LostPerson lostPerson)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lostPerson).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Gender = new SelectList(db.Gender, "Id", "Name", lostPerson.Gender);
            return View(lostPerson);
        }
        [Authorize(Roles = "Administrator")]
        // GET: LostPersons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LostPerson lostPerson = db.LostPerson.Find(id);
            if (lostPerson == null)
            {
                return HttpNotFound();
            }
            return View(lostPerson);
        }

        // POST: LostPersons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LostPerson lostPerson = db.LostPerson.Find(id);
            db.LostPerson.Remove(lostPerson);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RejestOsob/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("RejestOsobZaginionych", "Index", "LostPersons", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona główna", "Index", "LostPersons")</li>
                    <li>@Html.ActionLink("Informacje", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Moja aplikacja ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>